### ISSUE TITLE
Fabric version for Minecraft 1.16 crashes

### ISSUE THREAD

**Issue by dst0** [benfah/DoorsOfInfinity#15]
Hello benfah!
Fabric version for Minecraft 1.16 crashes on start.
I have all dependencies, but Doors of Infinity (version based on Fabric API) v1.0.6 causes error.
All info (zip file with dependencies and log file) attached here.
Please help.
[crash_details.zip](https://github.com/benfah/DoorsOfInfinity/files/4824844/crash_details.zip)

**Comment by ghost** [comment]
Can confirm. I have the same issue.

```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'doorsofinfinity'!
> 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
> 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
> 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
> 	at net.minecraft.class_310.<init>(class_310.java:425)
> 	at net.minecraft.client.main.Main.main(Main.java:177)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
> 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
> Caused by: java.lang.BootstrapMethodError: java.lang.IllegalAccessError: no such constructor: me.benfah.doorsofinfinity.block.entity.InfinityDoorBlockEntity.<init>()void/newInvokeSpecial
```

**Comment by ProsperCraft** [comment]
This can be closed because I can confirm this does not happen in the client or on a dedicated server any longer.
