### ISSUE TITLE
   Every time I click glass with a linked photon link my server crashes.

### ISSUE THREAD

**Issue by Tortilladog** [benfah/DoorsOfInfinity#29]
Every time I click glass with a linked photon link my server crashes.

**Comment by Tortilladog** [comment]
The crash report is:

---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 3/4/21 2:11 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.class_1160.method_23214(F)Lnet/minecraft/class_1158;
	at me.benfah.doorsofinfinity.item.PhotonLinkItem.method_7884(PhotonLinkItem.java:68)
	at net.minecraft.class_1799.method_7981(class_1799.java:227)
	at net.minecraft.class_3225.method_14262(class_3225.java:348)
	at net.minecraft.class_3244.method_12046(class_3244.java:1040)
	at net.minecraft.class_2885.method_12547(class_2885.java:36)
	at net.minecraft.class_2885.method_11054(class_2885.java:10)
	at net.minecraft.class_2600.method_11072(class_2600.java:21)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:144)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155)
	at net.minecraft.class_1255.method_16075(class_1255.java:118)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737)
	at net.minecraft.class_1255.method_18857(class_1255.java:127)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 4.15.0-128-generic
	Java Version: 1.8.0_271, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6558681648 bytes (6254 MB) / 10695475200 bytes (10200 MB) up to 10737418240 bytes (10240 MB)
	CPUs: 32
	JVM Flags: 21 total; -Xmx10240M -Xms512M -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:G1ReservePercent=20 -XX:G1HeapRegionSize=8M -XX:+UseG1GC -XX:+DisableExplicitGC -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1MixedGCLiveThresholdPercent=90 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -XX:+PerfDisableSharedMem -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:MaxTenuringThreshold=1 -Xss2M
	Fabric Mods: 
		adorn: Adorn 1.12.2+1.16.4
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		advdebug: Advancements Debug 2.2.0
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		appleskin: AppleSkin 1.0.11
		appliedenergistics2: Applied Energistics 2 8.1.0-alpha.13
		architectury: Architectury 1.3.81
		arstheurgia: Ars Theurgia 1.0.6
		artifacts: Artifacts 2.1.0+1.16.4-fabric
		artifice: Artifice 0.13.2+1.16.3
		artofalchemy: Art of Alchemy: Memoriam 1.0.0-rc4+1.16.4
		astromine: Astromine 1.11.5+fabric-1.16.5
		astromine-core: Astromine: Core 1.11.5+fabric-1.16.5
		astromine-discoveries: Astromine: Discoveries 1.11.5+fabric-1.16.5
		astromine-foundations: Astromine: Foundations 1.11.5+fabric-1.16.5
		astromine-technologies: Astromine: Technologies 1.11.5+fabric-1.16.5
		astromine-transportations: Astromine: Transportations 1.11.5+fabric-1.16.5
		autoconfig1u: Auto Config v1 Updated 3.3.1
		bambootweaks: Bamboo Tweaks unspecified
		battletowers: Battle Towers 3.3.2-1.16.4
		bedspreads: Bedspreads 1.3.1-1.16.4
		bettercaves: YUNG's Better Caves 1.16.2-1.0.3
		betterend: Better End 0.8.8-beta
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0
		betternether: Better Nether 5.0.7
		blade: Blade 2.0.0
		blast: BLAST 1.5
		blockshifter: Blockshifter 1.3.2+fabric-1.16.4
		blockus: Blockus 2.0.2+1.16.4
		blue_endless_jankson: jankson 1.2.0
		bunch-o-trinkets: Bunch O' Trinkets 1.0.1
		byg: BYG 1.1.3
		campanion: Campanion 1.3.1+build.51
		cardinal-components: Cardinal Components API 2.7.10
		cardinal-components-base: Cardinal Components API (base) 2.7.10
		cardinal-components-block: Cardinal Components API (blocks) 2.7.10
		cardinal-components-chunk: Cardinal Components API (chunks) 2.7.10
		cardinal-components-entity: Cardinal Components API (entities) 2.7.10
		cardinal-components-item: Cardinal Components API (items) 2.7.10
		cardinal-components-level: Cardinal Components API (world saves) 2.7.10
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.7.10
		cardinal-components-util: Cardinal Components API (utilities) 2.7.10
		cardinal-components-world: Cardinal Components API (worlds) 2.7.10
		carrier: Carrier 1.6.1
		cavebiomes: Cave Biomes 0.5.1
		chainmail: Chainmail 0.5.0
		charm: Charm 2.2.2
		charmonium: Charmonium 2.2.2
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		cinderscapes: Cinderscapes 1.3.0+build.51
		cleancut: CleanCut mc1.16-2.1-fabric
		cloth-api: Cloth API 1.4.9
		cloth-armor-api-v1: Cloth Armor API v1 1.4.9
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.9
		cloth-common-events-v1: Cloth Common Events v1 1.4.9
		cloth-config2: Cloth Config v4 4.8.3
		cloth-datagen-api-v1: Cloth Datagen v1 1.4.9
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.9
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.9
		cloth-utils-v1: Cloth Utils v1 1.4.9
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_github_nathanpb_safer: Safer 1.1.0
		com_github_therandomlabs_trlutils-config: TRLUtils-Config master-SNAPSHOT
		com_github_therandomlabs_trlutils-fabric: TRLUtils-Fabric 1.16-SNAPSHOT
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		compressedblocks: Compressed Blocks 1.0
		computercraft: CC:T for Fabric 1.91.2
		controlling: Controlling For Fabric 1.1.2
		cotton-config: Cotton Config 1.0.0-rc.7
		cotton-logging: Cotton Logging 1.0.0-rc.4
		couplings: Couplings 1.3.3
		crookedcrooks: Crooked Crooks 1.3.3+1.16.4
		croptopia: Croptopia 1.1.0
		crusade: Crusade 1.2.0
		dankstorage: Dank Storage 1.9a-1.16.3
		darkpaintings: Dark Paintings 1.0.0
		dawn: Dawn API 1.6.1
		decimal_coins: Decimal Coins 1.16.2-1.2.0
		diggusmaximus: Diggus Maximus 1.4.2-1.16.3
		dml-refabricated: Deep Mob Learning: Refabricated 0.3.1-beta5
		doorsofinfinity: Doors of Infinity 1.0.9-1.16.4
		dwarfcoal: Dwarf Coal 1.16.2-1.0.0
		elytra_swap: Elytra Swap 2.2.0-1.16.2
		expandedstorage: ExpandedStorage 5.6.31
		ezpas: Ezpas 1.2.3-1.16.2
		fabric: Fabric API 0.29.3+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
		fabric-commands-v0: Fabric Commands (v0) 0.2.1+cbe9176f3a
		fabric-containers-v0: Fabric Containers (v0) 0.1.9+a03e98793a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.2+8004b36d3a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
		fabric-furnaces: Fabric Furnaces 1.3.3-1.16.4
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.5+cbe9176f3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.2+cbe9176f3a
		fabric-language-kotlin: Fabric Language Kotlin 1.4.21+build.1
		fabric-language-scala: Fabric Language Scala 0.3.2.12
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+4358fbc63a
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.7+a03e98793a
		fabric-networking-v0: Fabric Networking (v0) 0.3.1+2a4333d33a
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
		fabric-particles-v1: Fabric Particles (v1) 0.2.3+cbe9176f3a
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.3+be155ae23a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.1+0d4d7e343a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.3+cbe9176f3a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
		fabricloader: Fabric Loader 0.11.1
		fallflyinglib: FallFlyingLib 1.1.0
		fatxporbs: Fat Experience Orbs 0.0.9
		fermion: Fermion 2.9.218
		fermion-gui: Fermion GUI 2.5.218
		fermion-modkeys: Fermion Modifier Keys 1.10.218
		fermion-orientation: Fermion Orientation 1.2.218
		fermion-simulator: Fermion Simulator 1.8.218
		fermion-varia: Fermion Varia 2.6.218
		fiber: fiber 0.23.0-2
		flamingo_ooo: Flamingo, oh, oh, oh... 1.0.4-MC1.16.3-fabric
		flonters: Flonters 1.1.1+1.16.2
		flora-doubling: Flora Doubling 1.3.0+1.16.4-fabric
		gameinfo: GameInfo 2.0.1b 1.16.4
		gateofbabylon: Gate Of Babylon 1.2.1-1.16.2
		geckolib: Geckolib 2.0.0
		geckolib3: Geckolib 3.0.3
		givemehats: Give Me Hats! 1.4
		glassdoor: Glass Doors 1.5.0-1.16
		glassential: Glassential 1.16.4-1.1.5
		goml: Get Off My Lawn 1.2.3-beta
		hard-hat-steve: Hard Hat Steve 1.2.0
		harvest: Harvest 1.2.12
		harvest_scythes: Harvest Scythes 1.0.8
		hctm-base: HCTM Base 3.5.0
		horseinfo: Horse Info 0.2.2-1.16.1
		ignis-fatuus: Ignis Fatuus 1.1.1
		imm_ptl_core: Immersive Portals Core 0.65
		immersive_portals: Immersive Portals 0.65
		improved-stations: Improved Stations 2.0.3
		indrev: Industrial Revolution 1.7.15-BETA
		inmis: Inmis 2.1.1-1.16.4
		inventorysorter: Inventory Sorter 1.7.6-1.16
		iron-jetpacks: Iron Jetpacks 0.2.5
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		javax_vecmath_vecmath: vecmath 1.5.2
		jumploader: Jumploader 2.1.2
		kibe: Kibe 1.6.1-BETA
		ktdatataglib: KtDataTagLib 1.4.0
		kubejs: KubeJS 1.5.5
		kyrptconfig: Kytpt Config 1.1.6-1.16
		lapisreserve: Lapis Reserve 1.0.6
		libblockattributes: LibBlockAttributes 0.8.4
		libblockattributes_core: LibBlockAttributes (Core) 0.8.5
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.5
		libblockattributes_items: LibBlockAttributes (Items) 0.8.5
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.2.2+1.16.3
		library_of_exile: Library of Exile 1.0.6
		libstructure: LibStructure 1.5
		lithium: Lithium 0.6.0
		lithium-api: Lithium API 0.6.0
		magna: Magna 1.4.3-1.16.2
		mcdict: MCDict 2.0.1+1.16.4
		megane: megane 3.1.2+1.16.4
		megane-api: megane-api 3.1.2+1.16.4
		megane-impl: megane-impl 3.1.2+1.16.4
		megane-runtime: megane-runtime 3.1.2+1.16.4
		minecraft: Minecraft 1.16.5
		mm: Manningham Mills 2.1
		mo_glass: Mo Glass 1.5-MC1.16.4
		modern_industrialization: Modern Industrialization 0.3.9
		mostructures: Mo' Structures 1.0.1+mc.1.16.4
		multi_item_lin: Multi Item Lin 1.0.0
		netherite_plus: Netherite Plus Mod 1.3.2-1.16.5
		nourish: Nourish 1.2.0
		org_codehaus_groovy_groovy: groovy 3.0.3
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.3
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		org_joml_joml: joml 1.10.0
		oro_config: OroArmor Config -0df99c92b1-1
		packages: Packages 1.1.1
		patchouli: Patchouli 1.16.4-48-FABRIC
		phonos: Phonos 0.1.1-beta
		phosphor: Phosphor 0.7.0+build.10
		piglib: Piglib 1.0.1
		playerabilitylib: Pal 1.2.1
		polymorph: Polymorph 0.0.7-1.16.4
		qcommon-cfg-core: qcommon-cfg-core 3.2.0
		qcommon-croco: Croco 2.1.1
		quickshulker: Quick Shulker 1.1.11-1.16
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		reborncore: Reborn Core 4.6.3+build.110
		repurposed_structures: Repurposed Structures 1.16.4-1.7.4
		respawnablepets: Respawnable Pets 1.16.4-1
		roughlyenoughitems: Roughly Enough Items 5.8.10
		roughlyenoughitems-api: REI (API) 5.8.10
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.8.10
		roughlyenoughitems-runtime: REI (Runtime) 5.8.10
		rswires: RSWires 4.10.0
		rtree-3i-lite-fabric: rtree-3i-lite for Fabric 0.3.0
		secretrooms: Secret Rooms 0.9.2+1.16.2
		shulkerboxtooltip: Shulker Box Tooltip 2.3.3+1.16.4
		simpleteleporters: Simple Teleporters 2.2.1
		simplexterrain: Simplex Terrain 0.7.2
		smootherbedrock: Smoother Bedrock 1.0.0
		special-circumstances: Special Circumstances 1.8.218
		staffofbuilding: Staff of Building 1.2.4-1.16.2
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stonecutter-tweaks: Stonecutter Tweaks 1.1.0-1.16
		strawdummy: Straw Dummy 1.4.0
		structure-helpers: Structure Helpers 3.0.0
		survivalisland: Survival Island 0.1.5
		tacocraft: TacoCraft 1.3.1+mc.1.16
		team_reborn_energy: Energy 0.1.1
		techreborn: Tech Reborn 3.7.3+build.192
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.0+build.1
		terraform-config-api-v1: Terraform Config API (v1) 1.0.0+build.1
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.0.0+build.1
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.0+build.1
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.0+build.4
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.0+build.1
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.1+build.4
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.0+build.1
		terrestria: Terrestria 2.1.5+build.28
		tis3d: TIS-3D 1.6.0
		tis3d-additions: TIS-3D Additions 0.2.1+1.16.2
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		totemmod: Wither Totems Mod 0.3.2
		trapexpansion: Trap Expansion 1.3.2
		traverse: Traverse 3.2.0+build.17
		trinkets: Trinkets 2.6.7
		truerooms: True Secret Rooms 1.1.2-hotfix
		vanilla-hammers: Vanilla Hammers 3.0.1-1.16.3
		vanilladeathchest: VanillaDeathChest 1.16.3-1.11.0.7-fabric
		vanillaexcavators: Vanilla Excavators 1.1.0
		villagerhats: Villager Hats fabric-1.16.4-1.0.1
		voyager: Voyager 1.0.0
		waila: Hwyla 1.9.22
		waystones: Waystones 1.1.1.1
		wild_explorer: Wild Explorer 1.3.1
		winged: Winged Mod 1.16.2-1.4.1
		wolveswitharmor: Wolves With Armor 1.5.2-1.16.2
		woodenhoppers: Wooden Hoppers 1.0.0
		woods_and_mires: Woods and Mires 1.0.4+1.16.3
		wrenchable: Wrenchable 1.0.0+1.16.1
		xaerominimap: Xaero's Minimap 21.1.0
		xaeroworldmap: Xaero's World Map 1.11.8
		yosbr: YOSBR 0.1.1
		yungsapi: YUNG's API 1.16.4-Fabric-1
	Player Count: 1 / 60; [class_3222['mdhminer'/34602, l='ServerWorld doorsofinfinity:infinity_dimension Silk _ Quarries', x=10.27, y=6.00, z=6.93]]
	Data Packs: vanilla (incompatible), Fabric Mods, phonos:data_pack, secretrooms:server_pack
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by srnyx** [comment]
This is a duplicate of https://github.com/benfah/DoorsOfInfinity/issues/14, please delete this issue
