### ISSUE TITLE
error on server and single player startup

### ISSUE THREAD

**Issue by slenderPanda** [benfah/DoorsOfInfinity#7]
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [doorsofinfinity.mixins.json:MixinMinecraftServer] from phase [DEFAULT] in config [doorsofinfinity.mixins.json] FAILED during APPLY
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:643)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:595)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
        ... 16 more

**Comment by slenderPanda** [comment]
this is for the newest snaption version for all

**Comment by benfah** [comment]
Can you send me your complete log, your MC version and the DoorsOfInfinity version?

**Comment by slenderPanda** [comment]
sure
1.0.6 doors to infinity
and 20w19a minecraft
https://pastebin.com/m5Y2VcuD
